mainwebapp/urls.py
from django.urls import path,include
from . import views 
from django.conf import settings 
from django.conf.urls.static import static 

app_name = 'mainwebapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('image_upload', views.plantdisease_image_view, name = 'image_upload'), 
    path('disease_images', views.display_disease_images, name = 'disease_images'), 
]


if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 

plantdiseasewebapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainwebapp.urls'))
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mainwebapp/models.py
from django.db import models

# Create your models here.
class PlantDiseaseImage(models.Model): 
	plantimage = models.ImageField(upload_to='images/')

mainwebapp/forms.py
from django import forms 
from .models import *
  
class PlantDiseaseForm(forms.ModelForm): 
  
    class Meta: 
        model = PlantDiseaseImage
        fields = ['plantimage']

mainwebapp/views.py
from django.shortcuts import render,redirect

from django.http import HttpResponse
# Create your views here.
from .forms import *
from keras.models import load_model
from keras.preprocessing import image
import numpy as np

def home(request):

	return render(request,'mainwebapp/home.html')

def prepare(img_path):
	#img = image.load_img(img_path, target_size=(256,256))
    img = image.load_img(img_path, target_size=(384,384))
    x = image.img_to_array(img)
    x = x/255
    return np.expand_dims(x, axis=0)

def plantdisease_image_view(request): 
  
    if request.method == 'POST': 
        form = PlantDiseaseForm(request.POST, request.FILES)
        if form.is_valid(): 
            form.save() 

        name=request.FILES['plantimage'].name
        #model=load_model('D:/finalyearprojectwebapp/plantdiseasewebapp/models/crop.h5')
        #model=load_model('D:/finalyearprojectwebapp/plantdiseasewebapp/models/plantddusingresnet50accuracy99.h5')
        model=load_model('./models/plantddusingresnet50of8epochs.h5')
        model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
        result = model.predict([prepare('./media/images/'+name)])
        classes=['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy']
        classresult=np.argmax(result,axis=1)
        a=classes[classresult[0]]
        return render(request, 'mainwebapp/disease.html', {'disease' :a })
    else: 
        form = PlantDiseaseForm()
    return render(request, 'mainwebapp/image_form.html', {'form' : form}) 
  



def display_disease_images(request): 
  
    if request.method == 'GET': 
  
        # getting all the objects of hotel. 
        Diseases = PlantDiseaseImage.objects.all()  
        return render(request, 'mainwebapp/displayimages.html', 
                     {'disease_images' : Diseases})

mainwebapp/templates/mainwebapp/disease.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>{{disease}}</h1>

<h3>click here to get solutions to solve this problem</h3>
<a href="">solution</a>
</body>
</html>

mainwebapp/templates/mainwebapp/displayimages.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <title>Hotel Images</title> 
  
      <meta name="viewport" content="width=device-width, initial-scale=1"> 
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> 
      </script> 
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"> 
      </script> 
</head> 
<body> 
  
    {% for disease in disease_images %} 
            <div class="col-md-4"> 
                     <img src="{{ disease.plantimage.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" /> 
            </div> 
    {% endfor %} 
  
</body> 
</html> 

mainwebapp/templates/mainwebapp/home.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>main page will be here</h1>
<a href="{% url 'mainwebapp:image_upload' %}">
<button >
	click here to upload pic and get results
</button>
</a>
</body>
</html>

mainwebapp/templates/mainwebapp/image_form.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <title>Hotel_image</title> 
</head> 
<body> 
    <form method = "post" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit">Upload</button> 
    </form> 
</body> 
</html> 